// Code generated by opencli. DO NOT EDIT.

package cligen

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/goccy/go-yaml"
	"github.com/spf13/cobra"
	"os"
	"time"
)

type CheckFailOn string

const (
	CheckFailOnFail CheckFailOn = "fail"
	CheckFailOnWarn CheckFailOn = "warn"
)

type CheckShow string

const (
	CheckShowAll      CheckShow = "all"
	CheckShowProblems CheckShow = "problems"
)

type CheckFormat string

const (
	CheckFormatChecklist CheckFormat = "checklist"
	CheckFormatTable     CheckFormat = "table"
	CheckFormatMarkdown  CheckFormat = "markdown"
	CheckFormatPlain     CheckFormat = "plain"
	CheckFormatJson      CheckFormat = "json"
	CheckFormatYaml      CheckFormat = "yaml"
)

type CheckParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Only             []string
	Skip             []string
	Offline          bool
	Register         bool
	Negative         bool
	Token            string
	RefreshToken     string
	ResourceUrl      []string
	FailOn           CheckFailOn
	Show             CheckShow
	Label            string
	Format           CheckFormat
	IssuerUrl        string
}
type CheckHandler func(ctx context.Context, cmd *cobra.Command, io IO, p CheckParams) (ConformanceReport, error)

func NewCheckCommand(check CheckHandler) CheckCommand {
	cmd := &cobra.Command{
		Use:   "check [url]",
		Short: "Audit an issuer against the OAuth and OpenID specifications.",
		Long: `Discovers everything the issuer publishes and runs a checklist of
conformance checks grouped by specification. Each specification is
reported as **supported and conformant**, **supported but
non-conformant**, **not supported**, or **not tested**.

Without credentials the checks are limited to what can be observed
anonymously: metadata, key sets, TLS, endpoint behaviour on bad input,
and the authorization endpoint's handling of a request without PKCE.

With a client id and secret the token endpoint is exercised: a client
credentials token is obtained, decoded, verified, introspected and
revoked; error responses are checked for shape; and DPoP, resource
indicators, PAR and the device flow are tried where advertised.

Checks that create state on the server, such as dynamic client
registration, are opt-in.
`,
		Aliases: []string{"audit", "conformance"},
		Example: `  # Anonymous audit of a public issuer.
  oauthcli check https://accounts.google.com
  # Full audit with credentials, including the checks that create state.
  oauthcli check --profile dev --register --negative
  # A report to paste into a pull request.
  oauthcli check --format markdown > report.md
  # Just the PKCE and OAuth 2.1 checks, for a script.
  oauthcli check --only rfc7636,oauth2.1 --format json`,
		Args: rangeArgs(0, 1),
	}

	var rawOnly []string
	cmd.Flags().StringSliceVar(&rawOnly, "only", nil, "Only run these specifications, by id such as rfc8414; repeatable.")
	var rawSkip []string
	cmd.Flags().StringSliceVar(&rawSkip, "skip", nil, "Skip these specifications; repeatable.")
	var rawOffline bool
	cmd.Flags().BoolVar(&rawOffline, "offline", false, "Do not send any request that needs credentials.")
	var rawRegister bool
	cmd.Flags().BoolVar(&rawRegister, "register", false, "Also test dynamic client registration by registering and deleting a client.")
	var rawNegative bool
	cmd.Flags().BoolVar(&rawNegative, "negative", false, "Also send a request with a wrong client secret to check the error response.")
	var rawToken string
	cmd.Flags().StringVar(&rawToken, "token", "", "An access token to validate against the issuer, instead of obtaining one.")
	var rawRefreshToken string
	cmd.Flags().StringVar(&rawRefreshToken, "refresh-token", "", "A refresh token to exercise the refresh_token grant with.")
	var rawResourceUrl []string
	cmd.Flags().StringArrayVar(&rawResourceUrl, "resource-url", nil, "A protected resource to check RFC 9728 metadata for; repeatable.")
	var rawFailOn string
	cmd.Flags().StringVar(&rawFailOn, "fail-on", "fail", "Exit 5 when a check of this level or worse exists: fail, warn.")
	var rawShow string
	cmd.Flags().StringVar(&rawShow, "show", "all", "Which checks to print: all, problems.")
	var rawLabel string
	cmd.Flags().StringVar(&rawLabel, "label", "", "Title for the report; defaults to the issuer.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "checklist", "Output format: checklist, table, markdown, plain, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var failOn CheckFailOn
		if rawFailOn != "" {
			switch rawFailOn {
			case "fail":
				failOn = CheckFailOnFail
			case "warn":
				failOn = CheckFailOnWarn
			default:
				return fmt.Errorf("invalid --fail-on %q: must be one of fail, warn", rawFailOn)
			}
		}
		var show CheckShow
		if rawShow != "" {
			switch rawShow {
			case "all":
				show = CheckShowAll
			case "problems":
				show = CheckShowProblems
			default:
				return fmt.Errorf("invalid --show %q: must be one of all, problems", rawShow)
			}
		}
		var format CheckFormat
		if rawFormat != "" {
			switch rawFormat {
			case "checklist":
				format = CheckFormatChecklist
			case "table":
				format = CheckFormatTable
			case "markdown":
				format = CheckFormatMarkdown
			case "plain":
				format = CheckFormatPlain
			case "json":
				format = CheckFormatJson
			case "yaml":
				format = CheckFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of checklist, table, markdown, plain, json, yaml", rawFormat)
			}
		}
		rawIssuerUrl := ""
		if len(args) > 0 {
			rawIssuerUrl = args[0]
		}

		p := CheckParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Only:             rawOnly,
			Skip:             rawSkip,
			Offline:          rawOffline,
			Register:         rawRegister,
			Negative:         rawNegative,
			Token:            rawToken,
			RefreshToken:     rawRefreshToken,
			ResourceUrl:      rawResourceUrl,
			FailOn:           failOn,
			Show:             show,
			Label:            rawLabel,
			Format:           format,
			IssuerUrl:        rawIssuerUrl,
		}

		result, err := check(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case CheckFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case CheckFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return CheckCommand(cmd)
}

type CheckCommand *cobra.Command
