// Code generated by opencli. DO NOT EDIT.

package cligen

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/goccy/go-yaml"
	"github.com/spf13/cobra"
	"os"
	"time"
)

type ClientRegisterTokenAuth string

const (
	ClientRegisterTokenAuthClientSecretBasic ClientRegisterTokenAuth = "client_secret_basic"
	ClientRegisterTokenAuthClientSecretPost  ClientRegisterTokenAuth = "client_secret_post"
	ClientRegisterTokenAuthPrivateKeyJwt     ClientRegisterTokenAuth = "private_key_jwt"
	ClientRegisterTokenAuthNone              ClientRegisterTokenAuth = "none"
)

type ClientRegisterFormat string

const (
	ClientRegisterFormatText ClientRegisterFormat = "text"
	ClientRegisterFormatJson ClientRegisterFormat = "json"
	ClientRegisterFormatYaml ClientRegisterFormat = "yaml"
)

type ClientRegisterParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	From             string
	ClientName       string
	GrantType        []string
	ResponseType     []string
	TokenAuth        ClientRegisterTokenAuth
	ClientUri        string
	LogoUri          string
	Contact          []string
	SoftwareId       string
	SoftwareVersion  string
	JwksUri          string
	InitialToken     string
	Param            []string
	Save             bool
	Reveal           bool
	Format           ClientRegisterFormat
}
type ClientRegisterHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ClientRegisterParams) (RegistrationReport, error)

func newClientRegisterCommand(clientRegister ClientRegisterHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "register",
		Short:   "Register a client at the registration endpoint.",
		Long:    "Builds a client metadata document from flags, or reads one with\n`--from`, and posts it to the `registration_endpoint`. An initial\naccess token can be supplied with `--initial-token` for servers that\nprotect registration.\n\nThe response is validated against RFC 7591: `client_id` must be\npresent, and every metadata value echoed back must be one the\nrequest asked for or a documented substitute. With `--save` the new\nclient id and secret are written into the active profile.\n",
		Aliases: []string{"new"},
		Example: `  # Register a loopback client and start using it.
  oauthcli client register -n "my test client" -r http://127.0.0.1:8085/callback --save
  # Register from a metadata document.
  oauthcli client register --from client.json --initial-token "$TOKEN"`,
		Args: rangeArgs(0, 0),
	}

	var rawFrom string
	cmd.Flags().StringVar(&rawFrom, "from", "", "Client metadata document to send, as a JSON file or - for stdin.")
	var rawClientName string
	cmd.Flags().StringVarP(&rawClientName, "client-name", "n", "", "Human-readable client name.")
	var rawGrantType []string
	cmd.Flags().StringSliceVar(&rawGrantType, "grant-type", nil, "Grant type the client will use; repeatable.")
	var rawResponseType []string
	cmd.Flags().StringSliceVar(&rawResponseType, "response-type", nil, "Response type the client will use; repeatable.")
	var rawTokenAuth string
	cmd.Flags().StringVar(&rawTokenAuth, "token-auth", "", "Requested token_endpoint_auth_method.")
	var rawClientUri string
	cmd.Flags().StringVar(&rawClientUri, "client-uri", "", "Home page of the client.")
	var rawLogoUri string
	cmd.Flags().StringVar(&rawLogoUri, "logo-uri", "", "Logo of the client.")
	var rawContact []string
	cmd.Flags().StringArrayVar(&rawContact, "contact", nil, "Contact e-mail; repeatable.")
	var rawSoftwareId string
	cmd.Flags().StringVar(&rawSoftwareId, "software-id", "", "Software identifier shared by every instance of this client.")
	var rawSoftwareVersion string
	cmd.Flags().StringVar(&rawSoftwareVersion, "software-version", "", "Version of the client software.")
	var rawJwksUri string
	cmd.Flags().StringVar(&rawJwksUri, "jwks-uri", "", "Key set of the client, for private_key_jwt or signed requests.")
	var rawInitialToken string
	cmd.Flags().StringVar(&rawInitialToken, "initial-token", "", "Initial access token that authorizes the registration.")
	var rawParam []string
	cmd.Flags().StringArrayVar(&rawParam, "param", nil, "Extra metadata member, as name=value or name=json; repeatable.")
	var rawSave bool
	cmd.Flags().BoolVar(&rawSave, "save", false, "Write the returned client id and secret into the active profile.")
	var rawReveal bool
	cmd.Flags().BoolVar(&rawReveal, "reveal", false, "Show the client secret and registration access token in full.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		if !cmd.Flags().Changed("initial-token") {
			if v := os.Getenv("OAUTH_INITIAL_TOKEN"); v != "" {
				_ = cmd.Flags().Set("initial-token", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var tokenAuth ClientRegisterTokenAuth
		if rawTokenAuth != "" {
			switch rawTokenAuth {
			case "client_secret_basic":
				tokenAuth = ClientRegisterTokenAuthClientSecretBasic
			case "client_secret_post":
				tokenAuth = ClientRegisterTokenAuthClientSecretPost
			case "private_key_jwt":
				tokenAuth = ClientRegisterTokenAuthPrivateKeyJwt
			case "none":
				tokenAuth = ClientRegisterTokenAuthNone
			default:
				return fmt.Errorf("invalid --token-auth %q: must be one of client_secret_basic, client_secret_post, private_key_jwt, none", rawTokenAuth)
			}
		}
		var format ClientRegisterFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = ClientRegisterFormatText
			case "json":
				format = ClientRegisterFormatJson
			case "yaml":
				format = ClientRegisterFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, json, yaml", rawFormat)
			}
		}

		p := ClientRegisterParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			From:             rawFrom,
			ClientName:       rawClientName,
			GrantType:        rawGrantType,
			ResponseType:     rawResponseType,
			TokenAuth:        tokenAuth,
			ClientUri:        rawClientUri,
			LogoUri:          rawLogoUri,
			Contact:          rawContact,
			SoftwareId:       rawSoftwareId,
			SoftwareVersion:  rawSoftwareVersion,
			JwksUri:          rawJwksUri,
			InitialToken:     rawInitialToken,
			Param:            rawParam,
			Save:             rawSave,
			Reveal:           rawReveal,
			Format:           format,
		}

		result, err := clientRegister(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case ClientRegisterFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case ClientRegisterFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

type ClientGetFormat string

const (
	ClientGetFormatText ClientGetFormat = "text"
	ClientGetFormatJson ClientGetFormat = "json"
	ClientGetFormatYaml ClientGetFormat = "yaml"
)

type ClientGetParams struct {
	Config            string
	Profile           string
	Issuer            string
	ClientId          string
	ClientSecret      string
	ClientSecretFile  string
	ClientKey         string
	AuthMethod        GlobalAuthMethod
	Scope             []string
	RedirectUri       string
	Audience          string
	Resource          []string
	TokenFile         string
	Header            []string
	Timeout           time.Duration
	Insecure          bool
	AllowHttp         bool
	Dpop              bool
	DpopKey           string
	Verbose           int
	Trace             bool
	NoColor           bool
	Theme             GlobalTheme
	RegistrationUri   string
	RegistrationToken string
	Reveal            bool
	Format            ClientGetFormat
}
type ClientGetHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ClientGetParams) (RegistrationReport, error)

func newClientGetCommand(clientGet ClientGetHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "get",
		Short:   "Read a registered client's configuration (RFC 7592).",
		Aliases: []string{"read"},
		Args:    rangeArgs(0, 0),
	}

	var rawRegistrationUri string
	cmd.Flags().StringVar(&rawRegistrationUri, "registration-uri", "", "The registration_client_uri of the client; defaults to the one saved in the profile.")
	var rawRegistrationToken string
	cmd.Flags().StringVar(&rawRegistrationToken, "registration-token", "", "The registration_access_token of the client; defaults to the one saved in the profile.")
	var rawReveal bool
	cmd.Flags().BoolVar(&rawReveal, "reveal", false, "Show the client secret in full.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		if !cmd.Flags().Changed("registration-token") {
			if v := os.Getenv("OAUTH_REGISTRATION_TOKEN"); v != "" {
				_ = cmd.Flags().Set("registration-token", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var format ClientGetFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = ClientGetFormatText
			case "json":
				format = ClientGetFormatJson
			case "yaml":
				format = ClientGetFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, json, yaml", rawFormat)
			}
		}

		p := ClientGetParams{
			Config:            rawConfig,
			Profile:           rawProfile,
			Issuer:            rawIssuer,
			ClientId:          rawClientId,
			ClientSecret:      rawClientSecret,
			ClientSecretFile:  rawClientSecretFile,
			ClientKey:         rawClientKey,
			AuthMethod:        authMethod,
			Scope:             rawScope,
			RedirectUri:       rawRedirectUri,
			Audience:          rawAudience,
			Resource:          rawResource,
			TokenFile:         rawTokenFile,
			Header:            rawHeader,
			Timeout:           rawTimeout,
			Insecure:          rawInsecure,
			AllowHttp:         rawAllowHttp,
			Dpop:              rawDpop,
			DpopKey:           rawDpopKey,
			Verbose:           rawVerbose,
			Trace:             rawTrace,
			NoColor:           rawNoColor,
			Theme:             theme,
			RegistrationUri:   rawRegistrationUri,
			RegistrationToken: rawRegistrationToken,
			Reveal:            rawReveal,
			Format:            format,
		}

		result, err := clientGet(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case ClientGetFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case ClientGetFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

type ClientUpdateFormat string

const (
	ClientUpdateFormatText ClientUpdateFormat = "text"
	ClientUpdateFormatJson ClientUpdateFormat = "json"
	ClientUpdateFormatYaml ClientUpdateFormat = "yaml"
)

type ClientUpdateParams struct {
	Config            string
	Profile           string
	Issuer            string
	ClientId          string
	ClientSecret      string
	ClientSecretFile  string
	ClientKey         string
	AuthMethod        GlobalAuthMethod
	Scope             []string
	RedirectUri       string
	Audience          string
	Resource          []string
	TokenFile         string
	Header            []string
	Timeout           time.Duration
	Insecure          bool
	AllowHttp         bool
	Dpop              bool
	DpopKey           string
	Verbose           int
	Trace             bool
	NoColor           bool
	Theme             GlobalTheme
	RegistrationUri   string
	RegistrationToken string
	From              string
	ClientName        string
	GrantType         []string
	Param             []string
	Reveal            bool
	Format            ClientUpdateFormat
}
type ClientUpdateHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ClientUpdateParams) (RegistrationReport, error)

func newClientUpdateCommand(clientUpdate ClientUpdateHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Replace a registered client's configuration (RFC 7592).",
		Long: `Reads the current configuration, applies the changes given, and
puts the whole document back, as RFC 7592 requires.
`,
		Args: rangeArgs(0, 0),
	}

	var rawRegistrationUri string
	cmd.Flags().StringVar(&rawRegistrationUri, "registration-uri", "", "The registration_client_uri of the client; defaults to the one saved in the profile.")
	var rawRegistrationToken string
	cmd.Flags().StringVar(&rawRegistrationToken, "registration-token", "", "The registration_access_token of the client; defaults to the one saved in the profile.")
	var rawFrom string
	cmd.Flags().StringVar(&rawFrom, "from", "", "Replacement metadata document, as a JSON file or - for stdin.")
	var rawClientName string
	cmd.Flags().StringVarP(&rawClientName, "client-name", "n", "", "New client name.")
	var rawGrantType []string
	cmd.Flags().StringSliceVar(&rawGrantType, "grant-type", nil, "New grant type list; repeatable.")
	var rawParam []string
	cmd.Flags().StringArrayVar(&rawParam, "param", nil, "Metadata member to set, as name=value or name=json; repeatable.")
	var rawReveal bool
	cmd.Flags().BoolVar(&rawReveal, "reveal", false, "Show the client secret in full.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		if !cmd.Flags().Changed("registration-token") {
			if v := os.Getenv("OAUTH_REGISTRATION_TOKEN"); v != "" {
				_ = cmd.Flags().Set("registration-token", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var format ClientUpdateFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = ClientUpdateFormatText
			case "json":
				format = ClientUpdateFormatJson
			case "yaml":
				format = ClientUpdateFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, json, yaml", rawFormat)
			}
		}

		p := ClientUpdateParams{
			Config:            rawConfig,
			Profile:           rawProfile,
			Issuer:            rawIssuer,
			ClientId:          rawClientId,
			ClientSecret:      rawClientSecret,
			ClientSecretFile:  rawClientSecretFile,
			ClientKey:         rawClientKey,
			AuthMethod:        authMethod,
			Scope:             rawScope,
			RedirectUri:       rawRedirectUri,
			Audience:          rawAudience,
			Resource:          rawResource,
			TokenFile:         rawTokenFile,
			Header:            rawHeader,
			Timeout:           rawTimeout,
			Insecure:          rawInsecure,
			AllowHttp:         rawAllowHttp,
			Dpop:              rawDpop,
			DpopKey:           rawDpopKey,
			Verbose:           rawVerbose,
			Trace:             rawTrace,
			NoColor:           rawNoColor,
			Theme:             theme,
			RegistrationUri:   rawRegistrationUri,
			RegistrationToken: rawRegistrationToken,
			From:              rawFrom,
			ClientName:        rawClientName,
			GrantType:         rawGrantType,
			Param:             rawParam,
			Reveal:            rawReveal,
			Format:            format,
		}

		result, err := clientUpdate(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case ClientUpdateFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case ClientUpdateFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

type ClientDeleteParams struct {
	Config            string
	Profile           string
	Issuer            string
	ClientId          string
	ClientSecret      string
	ClientSecretFile  string
	ClientKey         string
	AuthMethod        GlobalAuthMethod
	Scope             []string
	RedirectUri       string
	Audience          string
	Resource          []string
	TokenFile         string
	Header            []string
	Timeout           time.Duration
	Insecure          bool
	AllowHttp         bool
	Dpop              bool
	DpopKey           string
	Verbose           int
	Trace             bool
	NoColor           bool
	Theme             GlobalTheme
	RegistrationUri   string
	RegistrationToken string
	Yes               bool
}
type ClientDeleteHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ClientDeleteParams) error

func newClientDeleteCommand(clientDelete ClientDeleteHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "delete",
		Short:   "Deprovision a registered client (RFC 7592).",
		Aliases: []string{"rm"},
		Args:    rangeArgs(0, 0),
	}

	var rawRegistrationUri string
	cmd.Flags().StringVar(&rawRegistrationUri, "registration-uri", "", "The registration_client_uri of the client; defaults to the one saved in the profile.")
	var rawRegistrationToken string
	cmd.Flags().StringVar(&rawRegistrationToken, "registration-token", "", "The registration_access_token of the client; defaults to the one saved in the profile.")
	var rawYes bool
	cmd.Flags().BoolVarP(&rawYes, "yes", "y", false, "Skip the confirmation prompt.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		if !cmd.Flags().Changed("registration-token") {
			if v := os.Getenv("OAUTH_REGISTRATION_TOKEN"); v != "" {
				_ = cmd.Flags().Set("registration-token", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}

		p := ClientDeleteParams{
			Config:            rawConfig,
			Profile:           rawProfile,
			Issuer:            rawIssuer,
			ClientId:          rawClientId,
			ClientSecret:      rawClientSecret,
			ClientSecretFile:  rawClientSecretFile,
			ClientKey:         rawClientKey,
			AuthMethod:        authMethod,
			Scope:             rawScope,
			RedirectUri:       rawRedirectUri,
			Audience:          rawAudience,
			Resource:          rawResource,
			TokenFile:         rawTokenFile,
			Header:            rawHeader,
			Timeout:           rawTimeout,
			Insecure:          rawInsecure,
			AllowHttp:         rawAllowHttp,
			Dpop:              rawDpop,
			DpopKey:           rawDpopKey,
			Verbose:           rawVerbose,
			Trace:             rawTrace,
			NoColor:           rawNoColor,
			Theme:             theme,
			RegistrationUri:   rawRegistrationUri,
			RegistrationToken: rawRegistrationToken,
			Yes:               rawYes,
		}

		return clientDelete(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

func NewClientCommand(
	clientRegister ClientRegisterHandler,
	clientGet ClientGetHandler,
	clientUpdate ClientUpdateHandler,
	clientDelete ClientDeleteHandler,
) ClientCommand {
	cmd := &cobra.Command{
		Use:     "client",
		Short:   "Register and manage clients dynamically (RFC 7591, RFC 7592).",
		Aliases: []string{"dcr"},
		Args:    groupArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return cmd.Help()
		},
	}
	cmd.AddCommand(
		newClientRegisterCommand(clientRegister),
		newClientGetCommand(clientGet),
		newClientUpdateCommand(clientUpdate),
		newClientDeleteCommand(clientDelete),
	)
	return ClientCommand(cmd)
}

type ClientCommand *cobra.Command
