// Code generated by opencli. DO NOT EDIT.

package cligen

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/goccy/go-yaml"
	"github.com/spf13/cobra"
	"os"
	"time"
)

type ConfigInitParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Name             string
	NonInteractive   bool
	Force            bool
	Default          bool
}
type ConfigInitHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ConfigInitParams) error

func newConfigInitCommand(configInit ConfigInitHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Create a profile, interactively by default.",
		Long:  "Writes a profile into the configuration file. With no flags it asks\nfor each setting in a form, offering the scopes and client\nauthentication methods the issuer actually advertises.\n\nPass `--non-interactive` to write a profile from flags alone.\n",
		Example: `  # Set up a profile with the interactive form.
  oauthcli config init
  # Write a profile without prompting.
  oauthcli config init -n dev -i https://auth.example.com -c app --non-interactive`,
		Args: rangeArgs(0, 0),
	}

	var rawName string
	cmd.Flags().StringVarP(&rawName, "name", "n", "default", "Profile name to create or replace.")
	var rawNonInteractive bool
	cmd.Flags().BoolVar(&rawNonInteractive, "non-interactive", false, "Do not prompt; take every value from flags.")
	var rawForce bool
	cmd.Flags().BoolVar(&rawForce, "force", false, "Replace the profile if it already exists.")
	var rawDefault bool
	cmd.Flags().BoolVar(&rawDefault, "default", true, "Make this the default profile.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}

		p := ConfigInitParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Name:             rawName,
			NonInteractive:   rawNonInteractive,
			Force:            rawForce,
			Default:          rawDefault,
		}

		return configInit(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

type ConfigShowFormat string

const (
	ConfigShowFormatText ConfigShowFormat = "text"
	ConfigShowFormatJson ConfigShowFormat = "json"
	ConfigShowFormatYaml ConfigShowFormat = "yaml"
)

type ConfigShowParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Reveal           bool
	All              bool
	Format           ConfigShowFormat
}
type ConfigShowHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ConfigShowParams) error

func newConfigShowCommand(configShow ConfigShowHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "show",
		Short: "Show the settings a command would use.",
		Args:  rangeArgs(0, 0),
	}

	var rawReveal bool
	cmd.Flags().BoolVar(&rawReveal, "reveal", false, "Show secrets in full.")
	var rawAll bool
	cmd.Flags().BoolVar(&rawAll, "all", false, "Show the whole configuration file rather than the resolved settings.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var format ConfigShowFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = ConfigShowFormatText
			case "json":
				format = ConfigShowFormatJson
			case "yaml":
				format = ConfigShowFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, json, yaml", rawFormat)
			}
		}

		p := ConfigShowParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Reveal:           rawReveal,
			All:              rawAll,
			Format:           format,
		}

		return configShow(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

type ConfigListFormat string

const (
	ConfigListFormatTable ConfigListFormat = "table"
	ConfigListFormatPlain ConfigListFormat = "plain"
	ConfigListFormatJson  ConfigListFormat = "json"
	ConfigListFormatYaml  ConfigListFormat = "yaml"
)

type ConfigListParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Format           ConfigListFormat
}
type ConfigListHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ConfigListParams) (ProfileList, error)

func newConfigListCommand(configList ConfigListHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "list",
		Short:   "List the configured profiles.",
		Aliases: []string{"ls"},
		Args:    rangeArgs(0, 0),
	}

	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "table", "Output format: table, plain, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var format ConfigListFormat
		if rawFormat != "" {
			switch rawFormat {
			case "table":
				format = ConfigListFormatTable
			case "plain":
				format = ConfigListFormatPlain
			case "json":
				format = ConfigListFormatJson
			case "yaml":
				format = ConfigListFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of table, plain, json, yaml", rawFormat)
			}
		}

		p := ConfigListParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Format:           format,
		}

		result, err := configList(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case ConfigListFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case ConfigListFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

type ConfigUseParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Name             string
}
type ConfigUseHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ConfigUseParams) error

func newConfigUseCommand(configUse ConfigUseHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "use <profile>",
		Short: "Make a profile the default.",
		Args:  rangeArgs(1, 1),
	}

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		rawName := args[0]

		p := ConfigUseParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Name:             rawName,
		}

		return configUse(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

type ConfigSetParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Name             string
	Setting          string
	Value            string
}
type ConfigSetHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ConfigSetParams) error

func newConfigSetCommand(configSet ConfigSetHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "set <key> <value>",
		Short: "Change one setting of a profile.",
		Long:  "Sets a dotted key on the active profile, or on `--name`. Keys are\n`issuer`, `client.id`, `client.secret`, `client.secretFile`,\n`client.key`, `client.authMethod`, `scopes`, `redirectUri`,\n`audience`, `resources`, `insecure`, `allowHttp` and `description`.\n",
		Args:  rangeArgs(2, 2),
	}

	var rawName string
	cmd.Flags().StringVarP(&rawName, "name", "n", "", "Profile to change; defaults to the active profile.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		rawSetting := args[0]
		rawValue := args[1]

		p := ConfigSetParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Name:             rawName,
			Setting:          rawSetting,
			Value:            rawValue,
		}

		return configSet(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

type ConfigRemoveParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Yes              bool
	Name             string
}
type ConfigRemoveHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ConfigRemoveParams) error

func newConfigRemoveCommand(configRemove ConfigRemoveHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "remove <profile>",
		Short:   "Delete a profile and its saved token.",
		Aliases: []string{"rm"},
		Args:    rangeArgs(1, 1),
	}

	var rawYes bool
	cmd.Flags().BoolVarP(&rawYes, "yes", "y", false, "Skip the confirmation prompt.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		rawName := args[0]

		p := ConfigRemoveParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Yes:              rawYes,
			Name:             rawName,
		}

		return configRemove(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

type ConfigPathParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
}
type ConfigPathHandler func(ctx context.Context, cmd *cobra.Command, io IO, p ConfigPathParams) error

func newConfigPathCommand(configPath ConfigPathHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "path",
		Short: "Print the location of the configuration file.",
		Args:  rangeArgs(0, 0),
	}

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}

		p := ConfigPathParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
		}

		return configPath(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

func NewConfigCommand(
	configInit ConfigInitHandler,
	configShow ConfigShowHandler,
	configList ConfigListHandler,
	configUse ConfigUseHandler,
	configSet ConfigSetHandler,
	configRemove ConfigRemoveHandler,
	configPath ConfigPathHandler,
) ConfigCommand {
	cmd := &cobra.Command{
		Use:     "config",
		Short:   "Manage profiles in the configuration file.",
		Aliases: []string{"cfg"},
		Args:    groupArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return cmd.Help()
		},
	}
	cmd.AddCommand(
		newConfigInitCommand(configInit),
		newConfigShowCommand(configShow),
		newConfigListCommand(configList),
		newConfigUseCommand(configUse),
		newConfigSetCommand(configSet),
		newConfigRemoveCommand(configRemove),
		newConfigPathCommand(configPath),
	)
	return ConfigCommand(cmd)
}

type ConfigCommand *cobra.Command
