// Code generated by opencli. DO NOT EDIT.

package cligen

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/goccy/go-yaml"
	"github.com/spf13/cobra"
	"os"
	"time"
)

type FlowCodeResponseMode string

const (
	FlowCodeResponseModeQuery    FlowCodeResponseMode = "query"
	FlowCodeResponseModeFormPost FlowCodeResponseMode = "form_post"
	FlowCodeResponseModeFragment FlowCodeResponseMode = "fragment"
)

type FlowCodeFormat string

const (
	FlowCodeFormatText  FlowCodeFormat = "text"
	FlowCodeFormatPlain FlowCodeFormat = "plain"
	FlowCodeFormatJson  FlowCodeFormat = "json"
	FlowCodeFormatYaml  FlowCodeFormat = "yaml"
)

type FlowCodeParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Port             int
	NoBrowser        bool
	Manual           bool
	Par              bool
	NoPkce           bool
	Prompt           string
	LoginHint        string
	MaxAge           time.Duration
	ResponseMode     FlowCodeResponseMode
	State            string
	Nonce            string
	Param            []string
	Wait             time.Duration
	Save             bool
	NoVerify         bool
	Format           FlowCodeFormat
}
type FlowCodeHandler func(ctx context.Context, cmd *cobra.Command, io IO, p FlowCodeParams) (TokenResponse, error)

func newFlowCodeCommand(flowCode FlowCodeHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "code",
		Short:   "Run the authorization code flow with PKCE.",
		Long:    "Builds an authorization request with PKCE (S256), a fresh `state`\nand, when `openid` is in scope, a `nonce`; listens on the loopback\nredirect URI; opens the browser; exchanges the returned code; and\nvalidates the ID token.\n\n`--par` pushes the request first (RFC 9126) and sends only the\n`request_uri` to the browser. `--manual` prints the URL and waits\nfor the redirect URL to be pasted back, for a machine with no\nbrowser. The authorization URL is always printed to stderr so an\nagent can hand it to a person.\n\nThe redirect URI defaults to `http://127.0.0.1:<port>/callback`.\n",
		Aliases: []string{"authorization-code", "browser"},
		Example: `  # Log in with the browser and save the token.
  oauthcli flow code --profile dev
  # Push the request first and ask for an ID token.
  oauthcli flow code --scope openid,email --par
  # Headless machine, copy the URL by hand and paste the result.
  oauthcli flow code --manual --no-browser`,
		Args: rangeArgs(0, 0),
	}

	var rawPort int
	cmd.Flags().IntVar(&rawPort, "port", 0, "Loopback port to listen on (0 = pick a free one).")
	var rawNoBrowser bool
	cmd.Flags().BoolVar(&rawNoBrowser, "no-browser", false, "Print the authorization URL instead of opening a browser.")
	var rawManual bool
	cmd.Flags().BoolVar(&rawManual, "manual", false, "Do not listen; paste the redirect URL back when asked.")
	var rawPar bool
	cmd.Flags().BoolVar(&rawPar, "par", false, "Push the authorization request (RFC 9126) before redirecting.")
	var rawNoPkce bool
	cmd.Flags().BoolVar(&rawNoPkce, "no-pkce", false, "Omit PKCE. Only useful to prove that a server rejects it.")
	var rawPrompt string
	cmd.Flags().StringVar(&rawPrompt, "prompt", "", "Prompt parameter for OpenID Connect: none, login, consent, select_account.")
	var rawLoginHint string
	cmd.Flags().StringVar(&rawLoginHint, "login-hint", "", "Hint the identifier of the user to log in.")
	var rawMaxAge time.Duration
	cmd.Flags().DurationVar(&rawMaxAge, "max-age", mustParseDuration("0s"), "Maximum authentication age to request.")
	var rawResponseMode string
	cmd.Flags().StringVar(&rawResponseMode, "response-mode", "", "Response mode: query, form_post, fragment.")
	var rawState string
	cmd.Flags().StringVar(&rawState, "state", "", "Fixed state value; generated when absent.")
	var rawNonce string
	cmd.Flags().StringVar(&rawNonce, "nonce", "", "Fixed nonce value; generated when absent.")
	var rawParam []string
	cmd.Flags().StringArrayVar(&rawParam, "param", nil, "Extra authorization request parameter, as name=value; repeatable.")
	var rawWait time.Duration
	cmd.Flags().DurationVar(&rawWait, "wait", mustParseDuration("5m"), "How long to wait for the browser to come back.")
	var rawSave bool
	cmd.Flags().BoolVar(&rawSave, "save", true, "Save the token for the active profile so later commands can use it.")
	var rawNoVerify bool
	cmd.Flags().BoolVar(&rawNoVerify, "no-verify", false, "Do not verify JWT signatures.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, plain, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var responseMode FlowCodeResponseMode
		if rawResponseMode != "" {
			switch rawResponseMode {
			case "query":
				responseMode = FlowCodeResponseModeQuery
			case "form_post":
				responseMode = FlowCodeResponseModeFormPost
			case "fragment":
				responseMode = FlowCodeResponseModeFragment
			default:
				return fmt.Errorf("invalid --response-mode %q: must be one of query, form_post, fragment", rawResponseMode)
			}
		}
		var format FlowCodeFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = FlowCodeFormatText
			case "plain":
				format = FlowCodeFormatPlain
			case "json":
				format = FlowCodeFormatJson
			case "yaml":
				format = FlowCodeFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, plain, json, yaml", rawFormat)
			}
		}

		p := FlowCodeParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Port:             rawPort,
			NoBrowser:        rawNoBrowser,
			Manual:           rawManual,
			Par:              rawPar,
			NoPkce:           rawNoPkce,
			Prompt:           rawPrompt,
			LoginHint:        rawLoginHint,
			MaxAge:           rawMaxAge,
			ResponseMode:     responseMode,
			State:            rawState,
			Nonce:            rawNonce,
			Param:            rawParam,
			Wait:             rawWait,
			Save:             rawSave,
			NoVerify:         rawNoVerify,
			Format:           format,
		}

		result, err := flowCode(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case FlowCodeFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case FlowCodeFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

type FlowDeviceFormat string

const (
	FlowDeviceFormatText  FlowDeviceFormat = "text"
	FlowDeviceFormatPlain FlowDeviceFormat = "plain"
	FlowDeviceFormatJson  FlowDeviceFormat = "json"
	FlowDeviceFormatYaml  FlowDeviceFormat = "yaml"
)

type FlowDeviceParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	NoBrowser        bool
	Qr               bool
	Param            []string
	Save             bool
	NoVerify         bool
	Format           FlowDeviceFormat
}
type FlowDeviceHandler func(ctx context.Context, cmd *cobra.Command, io IO, p FlowDeviceParams) (TokenResponse, error)

func newFlowDeviceCommand(flowDevice FlowDeviceHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "device",
		Short: "Run the device authorization flow (RFC 8628).",
		Long:  "Requests a device code, shows the user code and verification URL\n(and a QR code, on request), then polls the token endpoint at the\ninterval the server asked for until the user approves, denies, or\nthe code expires. `slow_down` is honoured.\n",
		Example: `  # Log in from a device with no browser.
  oauthcli flow device --qr`,
		Args: rangeArgs(0, 0),
	}

	var rawNoBrowser bool
	cmd.Flags().BoolVar(&rawNoBrowser, "no-browser", false, "Do not open the verification URL in a browser.")
	var rawQr bool
	cmd.Flags().BoolVar(&rawQr, "qr", false, "Draw the verification URL as a QR code.")
	var rawParam []string
	cmd.Flags().StringArrayVar(&rawParam, "param", nil, "Extra device authorization parameter, as name=value; repeatable.")
	var rawSave bool
	cmd.Flags().BoolVar(&rawSave, "save", true, "Save the token for the active profile so later commands can use it.")
	var rawNoVerify bool
	cmd.Flags().BoolVar(&rawNoVerify, "no-verify", false, "Do not verify JWT signatures.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, plain, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var format FlowDeviceFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = FlowDeviceFormatText
			case "plain":
				format = FlowDeviceFormatPlain
			case "json":
				format = FlowDeviceFormatJson
			case "yaml":
				format = FlowDeviceFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, plain, json, yaml", rawFormat)
			}
		}

		p := FlowDeviceParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			NoBrowser:        rawNoBrowser,
			Qr:               rawQr,
			Param:            rawParam,
			Save:             rawSave,
			NoVerify:         rawNoVerify,
			Format:           format,
		}

		result, err := flowDevice(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case FlowDeviceFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case FlowDeviceFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

func NewFlowCommand(
	flowCode FlowCodeHandler,
	flowDevice FlowDeviceHandler,
) FlowCommand {
	cmd := &cobra.Command{
		Use:     "flow",
		Short:   "Run an interactive authorization flow.",
		Aliases: []string{"login", "auth"},
		Args:    groupArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return cmd.Help()
		},
	}
	cmd.AddCommand(
		newFlowCodeCommand(flowCode),
		newFlowDeviceCommand(flowDevice),
	)
	return FlowCommand(cmd)
}

type FlowCommand *cobra.Command
