// Code generated by opencli. DO NOT EDIT.

package cligen

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/goccy/go-yaml"
	"github.com/spf13/cobra"
	"os"
	"time"
)

type PkceFormat string

const (
	PkceFormatText  PkceFormat = "text"
	PkceFormatPlain PkceFormat = "plain"
	PkceFormatJson  PkceFormat = "json"
	PkceFormatYaml  PkceFormat = "yaml"
)

type PkceParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Verifier         string
	Length           int
	Format           PkceFormat
}
type PkceHandler func(ctx context.Context, cmd *cobra.Command, io IO, p PkceParams) (PkceResult, error)

func NewPkceCommand(pkce PkceHandler) PkceCommand {
	cmd := &cobra.Command{
		Use:   "pkce",
		Short: "Generate a PKCE verifier and challenge (RFC 7636).",
		Long:  "Prints a code verifier and its S256 challenge, for assembling an\nauthorization request by hand. Pass `--verifier` to compute the\nchallenge of an existing verifier.\n",
		Args:  rangeArgs(0, 0),
	}

	var rawVerifier string
	cmd.Flags().StringVar(&rawVerifier, "verifier", "", "Compute the challenge for this verifier instead of generating one.")
	var rawLength int
	cmd.Flags().IntVar(&rawLength, "length", 64, "Length of the generated verifier, 43 to 128.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, plain, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var format PkceFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = PkceFormatText
			case "plain":
				format = PkceFormatPlain
			case "json":
				format = PkceFormatJson
			case "yaml":
				format = PkceFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, plain, json, yaml", rawFormat)
			}
		}

		p := PkceParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Verifier:         rawVerifier,
			Length:           rawLength,
			Format:           format,
		}

		result, err := pkce(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case PkceFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case PkceFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return PkceCommand(cmd)
}

type PkceCommand *cobra.Command
