// Code generated by opencli. DO NOT EDIT.

package cligen

import (
	"github.com/spf13/cobra"
)

type GlobalAuthMethod string

const (
	GlobalAuthMethodAuto              GlobalAuthMethod = "auto"
	GlobalAuthMethodClientSecretBasic GlobalAuthMethod = "client_secret_basic"
	GlobalAuthMethodClientSecretPost  GlobalAuthMethod = "client_secret_post"
	GlobalAuthMethodClientSecretJwt   GlobalAuthMethod = "client_secret_jwt"
	GlobalAuthMethodPrivateKeyJwt     GlobalAuthMethod = "private_key_jwt"
	GlobalAuthMethodNone              GlobalAuthMethod = "none"
)

type GlobalTheme string

const (
	GlobalThemeCharm   GlobalTheme = "charm"
	GlobalThemeNord    GlobalTheme = "nord"
	GlobalThemeDracula GlobalTheme = "dracula"
	GlobalThemeMono    GlobalTheme = "mono"
)

func NewRootCommand(
	discover DiscoverCommand,
	metadata MetadataCommand,
	jwks JwksCommand,
	resource ResourceCommand,
	token TokenCommand,
	userinfo UserinfoCommand,
	flow FlowCommand,
	client ClientCommand,
	cimd CimdCommand,
	check CheckCommand,
	skill SkillCommand,
	reference ReferenceCommand,
	pkce PkceCommand,
	config ConfigCommand,
) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "oauthcli",
		Short: "Test, validate and exercise OAuth 2.0, OAuth 2.1 and OpenID Connect servers.",
		Long: `oauthcli is a terminal toolkit for OAuth 2.0, OAuth 2.1 and OpenID Connect,
built for people and for agents. It discovers what an authorization server
publishes, validates it against the RFCs, obtains and decodes tokens, runs
the interactive flows, registers clients, and audits a whole installation.

Start here (for AI agents):
  oauthcli skill                   Usage guide with workflows and copy-paste recipes
  oauthcli skill --full            Also include the full command reference
  oauthcli <command> --help        Every command explains itself and shows examples

The core loop:
  oauthcli discover URL            1. What does this issuer publish and support?
  oauthcli check URL               2. Is it conformant? A checklist per RFC.
  oauthcli token get --save        3. Get a token with the configured client.
  oauthcli token inspect           4. Decode and verify the saved token.
  oauthcli token expect --sub X    5. Assert facts about it; exit 5 on failure.

Point any command at a server with -i URL -c CLIENT_ID --client-secret-file F,
or save those once with "oauthcli config init" and pass -p PROFILE instead.
A token obtained with --save is used by later commands that take a TOKEN.

Every command has --format json (and yaml) with a documented schema, and
exit codes distinguish unreachable (2), OAuth error (3), not found (4),
failed expectation or non-conformance (5) and invalid token (6).

Results go to stdout, progress and warnings to stderr, so output pipes
cleanly: oauthcli token get -f plain | oauthcli token inspect -
`,
	}
	cmd.PersistentFlags().String("config", "", "Path to the configuration file.")
	cmd.PersistentFlags().StringP("profile", "p", "", "Configuration profile to use.")
	cmd.PersistentFlags().StringP("issuer", "i", "", "Issuer URL of the authorization server.")
	cmd.PersistentFlags().StringP("client-id", "c", "", "Identifier of the OAuth client.")
	cmd.PersistentFlags().String("client-secret", "", "Secret of the OAuth client.")
	cmd.PersistentFlags().String("client-secret-file", "", "Read the client secret from a file, or - for stdin.")
	cmd.PersistentFlags().String("client-key", "", "Private key in PEM form for private_key_jwt client authentication.")
	cmd.PersistentFlags().String("auth-method", "auto", "Client authentication method; auto picks from what the server advertises.")
	cmd.PersistentFlags().StringSliceP("scope", "s", nil, "Scope to request; repeatable, or separated by spaces or commas.")
	cmd.PersistentFlags().StringP("redirect-uri", "r", "", "Redirect URI of the client, used by the authorization code flow.")
	cmd.PersistentFlags().String("audience", "", "Audience to request, sent as the audience parameter.")
	cmd.PersistentFlags().StringArray("resource", nil, "Resource indicator (RFC 8707); repeatable.")
	cmd.PersistentFlags().String("token-file", "", "Read the token from a file, or - for stdin, when no TOKEN is given.")
	cmd.PersistentFlags().StringArrayP("header", "H", nil, "Extra HTTP header to send, as Name:Value; repeatable.")
	cmd.PersistentFlags().Duration("timeout", mustParseDuration("15s"), "Deadline for a single HTTP request.")
	cmd.PersistentFlags().Bool("insecure", false, "Accept a TLS certificate that fails verification.")
	cmd.PersistentFlags().Bool("allow-http", false, "Allow plain http URLs; otherwise only loopback addresses may use http.")
	cmd.PersistentFlags().Bool("dpop", false, "Bind tokens to a DPoP key (RFC 9449).")
	cmd.PersistentFlags().String("dpop-key", "", "Private key (EC or RSA) in PEM form to use for DPoP; generated when absent.")
	cmd.PersistentFlags().CountP("verbose", "v", "Increase log verbosity (-v, -vv).")
	cmd.PersistentFlags().Bool("trace", false, "Log every HTTP exchange on stderr, with secrets redacted.")
	cmd.PersistentFlags().Bool("no-color", false, "Disable colour and styling in output.")
	cmd.PersistentFlags().String("theme", "charm", "Colour theme: charm, nord, dracula, mono.")

	cmd.AddCommand(
		(*cobra.Command)(discover),
		(*cobra.Command)(metadata),
		(*cobra.Command)(jwks),
		(*cobra.Command)(resource),
		(*cobra.Command)(token),
		(*cobra.Command)(userinfo),
		(*cobra.Command)(flow),
		(*cobra.Command)(client),
		(*cobra.Command)(cimd),
		(*cobra.Command)(check),
		(*cobra.Command)(skill),
		(*cobra.Command)(reference),
		(*cobra.Command)(pkce),
		(*cobra.Command)(config),
	)

	return cmd
}
