// Code generated by opencli. DO NOT EDIT.

package cligen

import (
	"context"
	"fmt"
	"github.com/spf13/cobra"
	"os"
	"time"
)

type SkillParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Full             bool
	Out              string
}
type SkillHandler func(ctx context.Context, cmd *cobra.Command, io IO, p SkillParams) error

func NewSkillCommand(skill SkillHandler) SkillCommand {
	cmd := &cobra.Command{
		Use:     "skill",
		Short:   "Print the usage guide for agents, with workflows and recipes.",
		Long:    "Prints a Markdown guide that explains how to use this tool to reach a\ngoal: discover an issuer, audit it, obtain a token, decode and assert on\nit, run a browser or device login, and register a client. Read it before\nrunning other commands.\n\n`--full` appends a reference of every command, argument and flag,\ngenerated from the same specification the commands are built from.\n`--out DIR` writes the guide to DIR/SKILL.md so it can be installed as\nan agent skill.\n",
		Aliases: []string{"skills", "guide", "cookbook"},
		Example: `  # Read the guide.
  oauthcli skill
  # Install the guide as a project skill.
  oauthcli skill --full --out .claude/skills/oauth`,
		Args: rangeArgs(0, 0),
	}

	var rawFull bool
	cmd.Flags().BoolVar(&rawFull, "full", false, "Append the complete command reference.")
	var rawOut string
	cmd.Flags().StringVarP(&rawOut, "out", "o", "", "Directory to write SKILL.md into, instead of printing.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}

		p := SkillParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Full:             rawFull,
			Out:              rawOut,
		}

		return skill(cmd.Context(), cmd, newIO(cmd), p)
	}

	return SkillCommand(cmd)
}

type SkillCommand *cobra.Command
