// Code generated by opencli. DO NOT EDIT.

package cligen

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/goccy/go-yaml"
	"github.com/spf13/cobra"
	"os"
	"time"
)

type TokenGetGrant string

const (
	TokenGetGrantClientCredentials TokenGetGrant = "client_credentials"
	TokenGetGrantPassword          TokenGetGrant = "password"
	TokenGetGrantRefreshToken      TokenGetGrant = "refresh_token"
	TokenGetGrantJwtBearer         TokenGetGrant = "jwt-bearer"
	TokenGetGrantTokenExchange     TokenGetGrant = "token-exchange"
)

type TokenGetFormat string

const (
	TokenGetFormatText  TokenGetFormat = "text"
	TokenGetFormatPlain TokenGetFormat = "plain"
	TokenGetFormatJson  TokenGetFormat = "json"
	TokenGetFormatYaml  TokenGetFormat = "yaml"
)

type TokenGetParams struct {
	Config             string
	Profile            string
	Issuer             string
	ClientId           string
	ClientSecret       string
	ClientSecretFile   string
	ClientKey          string
	AuthMethod         GlobalAuthMethod
	Scope              []string
	RedirectUri        string
	Audience           string
	Resource           []string
	TokenFile          string
	Header             []string
	Timeout            time.Duration
	Insecure           bool
	AllowHttp          bool
	Dpop               bool
	DpopKey            string
	Verbose            int
	Trace              bool
	NoColor            bool
	Theme              GlobalTheme
	Grant              TokenGetGrant
	Username           string
	Password           string
	RefreshToken       string
	Assertion          string
	SubjectToken       string
	SubjectTokenType   string
	ActorToken         string
	ActorTokenType     string
	RequestedTokenType string
	Param              []string
	Save               bool
	NoVerify           bool
	Format             TokenGetFormat
}
type TokenGetHandler func(ctx context.Context, cmd *cobra.Command, io IO, p TokenGetParams) (TokenResponse, error)

func newTokenGetCommand(tokenGet TokenGetHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "get",
		Short:   "Obtain a token with a non-interactive grant.",
		Long:    "Posts to the token endpoint with the chosen grant and prints the\nresponse. The default grant is `client_credentials`.\n\nEvery access token that is a JWT is decoded and, when the issuer\npublishes a key set, its signature is verified. The response headers\nare checked against RFC 6749 §5.1 (`Cache-Control: no-store`).\n\n`password` is supported for testing legacy servers, with a warning:\nOAuth 2.1 removes it. `jwt-bearer` (RFC 7523) sends `--assertion`;\n`token-exchange` (RFC 8693) sends `--subject-token`.\n",
		Aliases: []string{"fetch"},
		Example: `  # Client credentials with a profile's client.
  oauthcli token get --profile api
  # One-off client credentials without a profile.
  oauthcli token get -i https://auth.example.com -c app --client-secret-file ./secret --scope read
  # Pipe the access token into the decoder.
  oauthcli token get --format plain | oauthcli token inspect -
  # Obtain a DPoP-bound token and keep it for later commands.
  oauthcli token get --dpop --save`,
		Args: rangeArgs(0, 0),
	}

	var rawGrant string
	cmd.Flags().StringVarP(&rawGrant, "grant", "g", "client_credentials", "Grant type.")
	var rawUsername string
	cmd.Flags().StringVarP(&rawUsername, "username", "u", "", "Resource owner user name, for the password grant.")
	var rawPassword string
	cmd.Flags().StringVar(&rawPassword, "password", "", "Resource owner password, for the password grant.")
	var rawRefreshToken string
	cmd.Flags().StringVar(&rawRefreshToken, "refresh-token", "", "Refresh token, for the refresh_token grant.")
	var rawAssertion string
	cmd.Flags().StringVar(&rawAssertion, "assertion", "", "Signed JWT assertion for the jwt-bearer grant.")
	var rawSubjectToken string
	cmd.Flags().StringVar(&rawSubjectToken, "subject-token", "", "Token to exchange, for the token-exchange grant.")
	var rawSubjectTokenType string
	cmd.Flags().StringVar(&rawSubjectTokenType, "subject-token-type", "urn:ietf:params:oauth:token-type:access_token", "Type of --subject-token.")
	var rawActorToken string
	cmd.Flags().StringVar(&rawActorToken, "actor-token", "", "Actor token, for delegation with the token-exchange grant.")
	var rawActorTokenType string
	cmd.Flags().StringVar(&rawActorTokenType, "actor-token-type", "urn:ietf:params:oauth:token-type:access_token", "Type of --actor-token.")
	var rawRequestedTokenType string
	cmd.Flags().StringVar(&rawRequestedTokenType, "requested-token-type", "", "Token type to request from a token exchange.")
	var rawParam []string
	cmd.Flags().StringArrayVar(&rawParam, "param", nil, "Extra form parameter to send, as name=value; repeatable.")
	var rawSave bool
	cmd.Flags().BoolVar(&rawSave, "save", false, "Save the token for the active profile so later commands can use it.")
	var rawNoVerify bool
	cmd.Flags().BoolVar(&rawNoVerify, "no-verify", false, "Do not verify the signature of a JWT access token.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, plain, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		if !cmd.Flags().Changed("password") {
			if v := os.Getenv("OAUTH_PASSWORD"); v != "" {
				_ = cmd.Flags().Set("password", v)
			}
		}
		if !cmd.Flags().Changed("refresh-token") {
			if v := os.Getenv("OAUTH_REFRESH_TOKEN"); v != "" {
				_ = cmd.Flags().Set("refresh-token", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var grant TokenGetGrant
		if rawGrant != "" {
			switch rawGrant {
			case "client_credentials":
				grant = TokenGetGrantClientCredentials
			case "password":
				grant = TokenGetGrantPassword
			case "refresh_token":
				grant = TokenGetGrantRefreshToken
			case "jwt-bearer":
				grant = TokenGetGrantJwtBearer
			case "token-exchange":
				grant = TokenGetGrantTokenExchange
			default:
				return fmt.Errorf("invalid --grant %q: must be one of client_credentials, password, refresh_token, jwt-bearer, token-exchange", rawGrant)
			}
		}
		var format TokenGetFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = TokenGetFormatText
			case "plain":
				format = TokenGetFormatPlain
			case "json":
				format = TokenGetFormatJson
			case "yaml":
				format = TokenGetFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, plain, json, yaml", rawFormat)
			}
		}

		p := TokenGetParams{
			Config:             rawConfig,
			Profile:            rawProfile,
			Issuer:             rawIssuer,
			ClientId:           rawClientId,
			ClientSecret:       rawClientSecret,
			ClientSecretFile:   rawClientSecretFile,
			ClientKey:          rawClientKey,
			AuthMethod:         authMethod,
			Scope:              rawScope,
			RedirectUri:        rawRedirectUri,
			Audience:           rawAudience,
			Resource:           rawResource,
			TokenFile:          rawTokenFile,
			Header:             rawHeader,
			Timeout:            rawTimeout,
			Insecure:           rawInsecure,
			AllowHttp:          rawAllowHttp,
			Dpop:               rawDpop,
			DpopKey:            rawDpopKey,
			Verbose:            rawVerbose,
			Trace:              rawTrace,
			NoColor:            rawNoColor,
			Theme:              theme,
			Grant:              grant,
			Username:           rawUsername,
			Password:           rawPassword,
			RefreshToken:       rawRefreshToken,
			Assertion:          rawAssertion,
			SubjectToken:       rawSubjectToken,
			SubjectTokenType:   rawSubjectTokenType,
			ActorToken:         rawActorToken,
			ActorTokenType:     rawActorTokenType,
			RequestedTokenType: rawRequestedTokenType,
			Param:              rawParam,
			Save:               rawSave,
			NoVerify:           rawNoVerify,
			Format:             format,
		}

		result, err := tokenGet(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case TokenGetFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case TokenGetFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

type TokenRefreshFormat string

const (
	TokenRefreshFormatText  TokenRefreshFormat = "text"
	TokenRefreshFormatPlain TokenRefreshFormat = "plain"
	TokenRefreshFormatJson  TokenRefreshFormat = "json"
	TokenRefreshFormatYaml  TokenRefreshFormat = "yaml"
)

type TokenRefreshParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Save             bool
	NoVerify         bool
	Format           TokenRefreshFormat
	RefreshToken     string
}
type TokenRefreshHandler func(ctx context.Context, cmd *cobra.Command, io IO, p TokenRefreshParams) (TokenResponse, error)

func newTokenRefreshCommand(tokenRefresh TokenRefreshHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "refresh [refresh-token]",
		Short: "Refresh a token.",
		Long:  "Posts a `refresh_token` grant. Without REFRESH_TOKEN the saved token\nof the active profile is refreshed, and the result replaces it when\n`--save` is set.\n\nThe response is checked for refresh token rotation, which OAuth 2.1\nrequires for public clients.\n",
		Args:  rangeArgs(0, 1),
	}

	var rawSave bool
	cmd.Flags().BoolVar(&rawSave, "save", false, "Replace the saved token of the active profile with the result.")
	var rawNoVerify bool
	cmd.Flags().BoolVar(&rawNoVerify, "no-verify", false, "Do not verify the signature of a JWT access token.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, plain, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var format TokenRefreshFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = TokenRefreshFormatText
			case "plain":
				format = TokenRefreshFormatPlain
			case "json":
				format = TokenRefreshFormatJson
			case "yaml":
				format = TokenRefreshFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, plain, json, yaml", rawFormat)
			}
		}
		rawRefreshToken := ""
		if len(args) > 0 {
			rawRefreshToken = args[0]
		}

		p := TokenRefreshParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Save:             rawSave,
			NoVerify:         rawNoVerify,
			Format:           format,
			RefreshToken:     rawRefreshToken,
		}

		result, err := tokenRefresh(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case TokenRefreshFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case TokenRefreshFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

type TokenInspectFormat string

const (
	TokenInspectFormatText TokenInspectFormat = "text"
	TokenInspectFormatJson TokenInspectFormat = "json"
	TokenInspectFormatYaml TokenInspectFormat = "yaml"
)

type TokenInspectParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Secret           string
	Keys             string
	NoVerify         bool
	IdToken          bool
	Format           TokenInspectFormat
	Token            string
}
type TokenInspectHandler func(ctx context.Context, cmd *cobra.Command, io IO, p TokenInspectParams) (TokenInfo, error)

func newTokenInspectCommand(tokenInspect TokenInspectHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "inspect [token]",
		Short:   "Decode a token and verify its signature and timestamps.",
		Long:    "Decodes a JWT and prints its header and claims with timestamps in\nhuman terms. When the token carries an `iss` claim, or an issuer is\nconfigured, the signature is verified against the issuer's key set.\n`--secret` verifies an HMAC-signed token instead.\n\nAn opaque token is reported as such, with a hint to use\n`token introspect`.\n\nWithout TOKEN the saved token of the active profile is inspected; a\nTOKEN of `-` reads it from stdin, which keeps it out of shell history.\n",
		Aliases: []string{"decode", "show"},
		Example: `  # Decode and verify a token.
  oauthcli token inspect eyJhbGciOi...
  # Read the token from stdin.
  oauthcli token inspect - < token.txt
  # Pull one claim from the saved token.
  oauthcli token inspect --format json | jq .claims.sub`,
		Args: rangeArgs(0, 1),
	}

	var rawSecret string
	cmd.Flags().StringVar(&rawSecret, "secret", "", "Shared secret for verifying an HMAC-signed token.")
	var rawKeys string
	cmd.Flags().StringVar(&rawKeys, "keys", "", "Key set to verify against, as a URL or file path, instead of the issuer's.")
	var rawNoVerify bool
	cmd.Flags().BoolVar(&rawNoVerify, "no-verify", false, "Decode only; do not verify the signature.")
	var rawIdToken bool
	cmd.Flags().BoolVar(&rawIdToken, "id-token", false, "Treat the token as an ID token and apply the OpenID Connect validation rules.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var format TokenInspectFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = TokenInspectFormatText
			case "json":
				format = TokenInspectFormatJson
			case "yaml":
				format = TokenInspectFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, json, yaml", rawFormat)
			}
		}
		rawToken := ""
		if len(args) > 0 {
			rawToken = args[0]
		}

		p := TokenInspectParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Secret:           rawSecret,
			Keys:             rawKeys,
			NoVerify:         rawNoVerify,
			IdToken:          rawIdToken,
			Format:           format,
			Token:            rawToken,
		}

		result, err := tokenInspect(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case TokenInspectFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case TokenInspectFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

type TokenIntrospectHint string

const (
	TokenIntrospectHintAccessToken  TokenIntrospectHint = "access_token"
	TokenIntrospectHintRefreshToken TokenIntrospectHint = "refresh_token"
)

type TokenIntrospectFormat string

const (
	TokenIntrospectFormatText TokenIntrospectFormat = "text"
	TokenIntrospectFormatJson TokenIntrospectFormat = "json"
	TokenIntrospectFormatYaml TokenIntrospectFormat = "yaml"
)

type TokenIntrospectParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Hint             TokenIntrospectHint
	Format           TokenIntrospectFormat
	Token            string
}
type TokenIntrospectHandler func(ctx context.Context, cmd *cobra.Command, io IO, p TokenIntrospectParams) (IntrospectionReport, error)

func newTokenIntrospectCommand(tokenIntrospect TokenIntrospectHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "introspect [token]",
		Short: "Ask the server about a token (RFC 7662).",
		Long: `Posts the token to the introspection endpoint with the client's
credentials and prints the response. The response is checked for
the members RFC 7662 requires, and its claims are compared with the
token's own claims when it is a JWT.
`,
		Args: rangeArgs(0, 1),
	}

	var rawHint string
	cmd.Flags().StringVar(&rawHint, "hint", "", "Value of token_type_hint: access_token, refresh_token.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var hint TokenIntrospectHint
		if rawHint != "" {
			switch rawHint {
			case "access_token":
				hint = TokenIntrospectHintAccessToken
			case "refresh_token":
				hint = TokenIntrospectHintRefreshToken
			default:
				return fmt.Errorf("invalid --hint %q: must be one of access_token, refresh_token", rawHint)
			}
		}
		var format TokenIntrospectFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = TokenIntrospectFormatText
			case "json":
				format = TokenIntrospectFormatJson
			case "yaml":
				format = TokenIntrospectFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, json, yaml", rawFormat)
			}
		}
		rawToken := ""
		if len(args) > 0 {
			rawToken = args[0]
		}

		p := TokenIntrospectParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Hint:             hint,
			Format:           format,
			Token:            rawToken,
		}

		result, err := tokenIntrospect(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case TokenIntrospectFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case TokenIntrospectFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

type TokenRevokeHint string

const (
	TokenRevokeHintAccessToken  TokenRevokeHint = "access_token"
	TokenRevokeHintRefreshToken TokenRevokeHint = "refresh_token"
)

type TokenRevokeFormat string

const (
	TokenRevokeFormatText TokenRevokeFormat = "text"
	TokenRevokeFormatJson TokenRevokeFormat = "json"
	TokenRevokeFormatYaml TokenRevokeFormat = "yaml"
)

type TokenRevokeParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Hint             TokenRevokeHint
	Verify           bool
	Forget           bool
	Format           TokenRevokeFormat
	Token            string
}
type TokenRevokeHandler func(ctx context.Context, cmd *cobra.Command, io IO, p TokenRevokeParams) (RevocationReport, error)

func newTokenRevokeCommand(tokenRevoke TokenRevokeHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "revoke [token]",
		Short: "Revoke a token (RFC 7009).",
		Long:  "Posts the token to the revocation endpoint. A conformant server\nanswers 200 whether or not the token was valid, so success here\nmeans \"the server accepted the request\", and `--verify` follows up\nwith an introspection to confirm the token is inactive.\n",
		Args:  rangeArgs(0, 1),
	}

	var rawHint string
	cmd.Flags().StringVar(&rawHint, "hint", "", "Value of token_type_hint: access_token, refresh_token.")
	var rawVerify bool
	cmd.Flags().BoolVar(&rawVerify, "verify", false, "Introspect the token afterwards to confirm it is inactive.")
	var rawForget bool
	cmd.Flags().BoolVar(&rawForget, "forget", false, "Also delete the saved token of the active profile.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var hint TokenRevokeHint
		if rawHint != "" {
			switch rawHint {
			case "access_token":
				hint = TokenRevokeHintAccessToken
			case "refresh_token":
				hint = TokenRevokeHintRefreshToken
			default:
				return fmt.Errorf("invalid --hint %q: must be one of access_token, refresh_token", rawHint)
			}
		}
		var format TokenRevokeFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = TokenRevokeFormatText
			case "json":
				format = TokenRevokeFormatJson
			case "yaml":
				format = TokenRevokeFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, json, yaml", rawFormat)
			}
		}
		rawToken := ""
		if len(args) > 0 {
			rawToken = args[0]
		}

		p := TokenRevokeParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Hint:             hint,
			Verify:           rawVerify,
			Forget:           rawForget,
			Format:           format,
			Token:            rawToken,
		}

		result, err := tokenRevoke(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case TokenRevokeFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case TokenRevokeFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

type TokenExpectFormat string

const (
	TokenExpectFormatText TokenExpectFormat = "text"
	TokenExpectFormatJson TokenExpectFormat = "json"
	TokenExpectFormatYaml TokenExpectFormat = "yaml"
)

type TokenExpectParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Claim            []string
	Has              []string
	Missing          []string
	Sub              string
	Aud              []string
	Iss              string
	Alg              string
	Typ              string
	ScopeIncludes    []string
	MinTtl           time.Duration
	MaxTtl           time.Duration
	AllowExpired     bool
	NoVerify         bool
	Active           bool
	Quiet            bool
	Format           TokenExpectFormat
	Token            string
}
type TokenExpectHandler func(ctx context.Context, cmd *cobra.Command, io IO, p TokenExpectParams) (ExpectationReport, error)

func newTokenExpectCommand(tokenExpect TokenExpectHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "expect [token]",
		Short:   "Assert facts about a token; exit 5 when one does not hold.",
		Long:    "Decodes the token and checks every expectation given. The command\nexits 0 when all hold and 5 when any fails, so it slots into a test\nscript or an agent's plan.\n\n`--claim name=value` requires equality with the string form of the\nclaim; `--claim name~pattern` requires a regular expression match;\n`--claim aud+=api` requires membership in an array claim. `--has`\nand `--missing` check presence. Signature verification and expiry\nare checked by default.\n",
		Aliases: []string{"assert", "test"},
		Example: `  # Check the saved token's subject, audience and scope.
  oauthcli token expect --sub 1234 --aud https://api.example.com --scope-includes read
  # Regular expression and header checks on a token from stdin.
  oauthcli token expect - --claim 'email~@example\.com$' --typ at+jwt < token.txt`,
		Args: rangeArgs(0, 1),
	}

	var rawClaim []string
	cmd.Flags().StringArrayVar(&rawClaim, "claim", nil, "Expected claim, as name=value, name~regex or name+=member; repeatable.")
	var rawHas []string
	cmd.Flags().StringArrayVar(&rawHas, "has", nil, "Claim that must be present; repeatable.")
	var rawMissing []string
	cmd.Flags().StringArrayVar(&rawMissing, "missing", nil, "Claim that must be absent; repeatable.")
	var rawSub string
	cmd.Flags().StringVar(&rawSub, "sub", "", "Expected subject.")
	var rawAud []string
	cmd.Flags().StringArrayVar(&rawAud, "aud", nil, "Audience the token must include; repeatable.")
	var rawIss string
	cmd.Flags().StringVar(&rawIss, "iss", "", "Expected issuer. Defaults to the configured issuer when one is known.")
	var rawAlg string
	cmd.Flags().StringVar(&rawAlg, "alg", "", "Expected signing algorithm.")
	var rawTyp string
	cmd.Flags().StringVar(&rawTyp, "typ", "", "Expected JOSE header type, e.g. at+jwt.")
	var rawScopeIncludes []string
	cmd.Flags().StringArrayVar(&rawScopeIncludes, "scope-includes", nil, "Scope that must be granted; repeatable.")
	var rawMinTtl time.Duration
	cmd.Flags().DurationVar(&rawMinTtl, "min-ttl", mustParseDuration("0s"), "Minimum remaining lifetime.")
	var rawMaxTtl time.Duration
	cmd.Flags().DurationVar(&rawMaxTtl, "max-ttl", mustParseDuration("0s"), "Maximum total lifetime from iat to exp.")
	var rawAllowExpired bool
	cmd.Flags().BoolVar(&rawAllowExpired, "allow-expired", false, "Do not fail on an expired token.")
	var rawNoVerify bool
	cmd.Flags().BoolVar(&rawNoVerify, "no-verify", false, "Do not require a valid signature.")
	var rawActive bool
	cmd.Flags().BoolVar(&rawActive, "active", false, "Also require the introspection endpoint to report the token active.")
	var rawQuiet bool
	cmd.Flags().BoolVarP(&rawQuiet, "quiet", "q", false, "Print nothing; the exit code is the result.")
	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var format TokenExpectFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = TokenExpectFormatText
			case "json":
				format = TokenExpectFormatJson
			case "yaml":
				format = TokenExpectFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, json, yaml", rawFormat)
			}
		}
		rawToken := ""
		if len(args) > 0 {
			rawToken = args[0]
		}

		p := TokenExpectParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Claim:            rawClaim,
			Has:              rawHas,
			Missing:          rawMissing,
			Sub:              rawSub,
			Aud:              rawAud,
			Iss:              rawIss,
			Alg:              rawAlg,
			Typ:              rawTyp,
			ScopeIncludes:    rawScopeIncludes,
			MinTtl:           rawMinTtl,
			MaxTtl:           rawMaxTtl,
			AllowExpired:     rawAllowExpired,
			NoVerify:         rawNoVerify,
			Active:           rawActive,
			Quiet:            rawQuiet,
			Format:           format,
			Token:            rawToken,
		}

		result, err := tokenExpect(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case TokenExpectFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case TokenExpectFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

type TokenStatusFormat string

const (
	TokenStatusFormatText  TokenStatusFormat = "text"
	TokenStatusFormatTable TokenStatusFormat = "table"
	TokenStatusFormatPlain TokenStatusFormat = "plain"
	TokenStatusFormatJson  TokenStatusFormat = "json"
	TokenStatusFormatYaml  TokenStatusFormat = "yaml"
)

type TokenStatusParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	Format           TokenStatusFormat
}
type TokenStatusHandler func(ctx context.Context, cmd *cobra.Command, io IO, p TokenStatusParams) (TokenStatusList, error)

func newTokenStatusCommand(tokenStatus TokenStatusHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "status",
		Short: "Show the tokens saved for each profile.",
		Args:  rangeArgs(0, 0),
	}

	var rawFormat string
	cmd.Flags().StringVarP(&rawFormat, "format", "f", "text", "Output format: text, table, plain, json, yaml.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}
		var format TokenStatusFormat
		if rawFormat != "" {
			switch rawFormat {
			case "text":
				format = TokenStatusFormatText
			case "table":
				format = TokenStatusFormatTable
			case "plain":
				format = TokenStatusFormatPlain
			case "json":
				format = TokenStatusFormatJson
			case "yaml":
				format = TokenStatusFormatYaml
			default:
				return fmt.Errorf("invalid --format %q: must be one of text, table, plain, json, yaml", rawFormat)
			}
		}

		p := TokenStatusParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			Format:           format,
		}

		result, err := tokenStatus(cmd.Context(), cmd, newIO(cmd), p)
		if err != nil {
			return err
		}
		switch format {
		case TokenStatusFormatJson:
			return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
		case TokenStatusFormatYaml:
			enc := yaml.NewEncoder(cmd.OutOrStdout())
			if err := enc.Encode(result); err != nil {
				return err
			}
			return enc.Close()
		}
		return nil
	}

	return cmd
}

type TokenClearParams struct {
	Config           string
	Profile          string
	Issuer           string
	ClientId         string
	ClientSecret     string
	ClientSecretFile string
	ClientKey        string
	AuthMethod       GlobalAuthMethod
	Scope            []string
	RedirectUri      string
	Audience         string
	Resource         []string
	TokenFile        string
	Header           []string
	Timeout          time.Duration
	Insecure         bool
	AllowHttp        bool
	Dpop             bool
	DpopKey          string
	Verbose          int
	Trace            bool
	NoColor          bool
	Theme            GlobalTheme
	All              bool
}
type TokenClearHandler func(ctx context.Context, cmd *cobra.Command, io IO, p TokenClearParams) error

func newTokenClearCommand(tokenClear TokenClearHandler) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "clear",
		Short:   "Delete the saved token of the active profile, or of every profile.",
		Aliases: []string{"forget", "logout"},
		Args:    rangeArgs(0, 0),
	}

	var rawAll bool
	cmd.Flags().BoolVar(&rawAll, "all", false, "Delete the saved tokens of every profile.")

	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if !cmd.Flags().Changed("config") {
			if v := os.Getenv("OAUTH_CONFIG"); v != "" {
				_ = cmd.Flags().Set("config", v)
			}
		}
		if !cmd.Flags().Changed("profile") {
			if v := os.Getenv("OAUTH_PROFILE"); v != "" {
				_ = cmd.Flags().Set("profile", v)
			}
		}
		if !cmd.Flags().Changed("issuer") {
			if v := os.Getenv("OAUTH_ISSUER"); v != "" {
				_ = cmd.Flags().Set("issuer", v)
			}
		}
		if !cmd.Flags().Changed("client-id") {
			if v := os.Getenv("OAUTH_CLIENT_ID"); v != "" {
				_ = cmd.Flags().Set("client-id", v)
			}
		}
		if !cmd.Flags().Changed("client-secret") {
			if v := os.Getenv("OAUTH_CLIENT_SECRET"); v != "" {
				_ = cmd.Flags().Set("client-secret", v)
			}
		}
		if !cmd.Flags().Changed("client-key") {
			if v := os.Getenv("OAUTH_CLIENT_KEY"); v != "" {
				_ = cmd.Flags().Set("client-key", v)
			}
		}
		if !cmd.Flags().Changed("scope") {
			if v := os.Getenv("OAUTH_SCOPE"); v != "" {
				_ = cmd.Flags().Set("scope", v)
			}
		}
		if !cmd.Flags().Changed("redirect-uri") {
			if v := os.Getenv("OAUTH_REDIRECT_URI"); v != "" {
				_ = cmd.Flags().Set("redirect-uri", v)
			}
		}
		if !cmd.Flags().Changed("audience") {
			if v := os.Getenv("OAUTH_AUDIENCE"); v != "" {
				_ = cmd.Flags().Set("audience", v)
			}
		}
		if !cmd.Flags().Changed("timeout") {
			if v := os.Getenv("OAUTH_TIMEOUT"); v != "" {
				_ = cmd.Flags().Set("timeout", v)
			}
		}
		if !cmd.Flags().Changed("no-color") {
			if v := os.Getenv("NO_COLOR"); v != "" {
				_ = cmd.Flags().Set("no-color", v)
			}
		}
		if !cmd.Flags().Changed("theme") {
			if v := os.Getenv("OAUTH_THEME"); v != "" {
				_ = cmd.Flags().Set("theme", v)
			}
		}
		rawConfig, _ := cmd.Flags().GetString("config")
		rawProfile, _ := cmd.Flags().GetString("profile")
		rawIssuer, _ := cmd.Flags().GetString("issuer")
		rawClientId, _ := cmd.Flags().GetString("client-id")
		rawClientSecret, _ := cmd.Flags().GetString("client-secret")
		rawClientSecretFile, _ := cmd.Flags().GetString("client-secret-file")
		rawClientKey, _ := cmd.Flags().GetString("client-key")
		rawAuthMethod, _ := cmd.Flags().GetString("auth-method")
		var authMethod GlobalAuthMethod
		if rawAuthMethod != "" {
			switch rawAuthMethod {
			case "auto":
				authMethod = GlobalAuthMethodAuto
			case "client_secret_basic":
				authMethod = GlobalAuthMethodClientSecretBasic
			case "client_secret_post":
				authMethod = GlobalAuthMethodClientSecretPost
			case "client_secret_jwt":
				authMethod = GlobalAuthMethodClientSecretJwt
			case "private_key_jwt":
				authMethod = GlobalAuthMethodPrivateKeyJwt
			case "none":
				authMethod = GlobalAuthMethodNone
			default:
				return fmt.Errorf("invalid --auth-method %q: must be one of auto, client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt, none", rawAuthMethod)
			}
		}
		rawScope, _ := cmd.Flags().GetStringSlice("scope")
		rawRedirectUri, _ := cmd.Flags().GetString("redirect-uri")
		rawAudience, _ := cmd.Flags().GetString("audience")
		rawResource, _ := cmd.Flags().GetStringArray("resource")
		rawTokenFile, _ := cmd.Flags().GetString("token-file")
		rawHeader, _ := cmd.Flags().GetStringArray("header")
		rawTimeout, _ := cmd.Flags().GetDuration("timeout")
		rawInsecure, _ := cmd.Flags().GetBool("insecure")
		rawAllowHttp, _ := cmd.Flags().GetBool("allow-http")
		rawDpop, _ := cmd.Flags().GetBool("dpop")
		rawDpopKey, _ := cmd.Flags().GetString("dpop-key")
		rawVerbose, _ := cmd.Flags().GetCount("verbose")
		rawTrace, _ := cmd.Flags().GetBool("trace")
		rawNoColor, _ := cmd.Flags().GetBool("no-color")
		rawTheme, _ := cmd.Flags().GetString("theme")
		var theme GlobalTheme
		if rawTheme != "" {
			switch rawTheme {
			case "charm":
				theme = GlobalThemeCharm
			case "nord":
				theme = GlobalThemeNord
			case "dracula":
				theme = GlobalThemeDracula
			case "mono":
				theme = GlobalThemeMono
			default:
				return fmt.Errorf("invalid --theme %q: must be one of charm, nord, dracula, mono", rawTheme)
			}
		}

		p := TokenClearParams{
			Config:           rawConfig,
			Profile:          rawProfile,
			Issuer:           rawIssuer,
			ClientId:         rawClientId,
			ClientSecret:     rawClientSecret,
			ClientSecretFile: rawClientSecretFile,
			ClientKey:        rawClientKey,
			AuthMethod:       authMethod,
			Scope:            rawScope,
			RedirectUri:      rawRedirectUri,
			Audience:         rawAudience,
			Resource:         rawResource,
			TokenFile:        rawTokenFile,
			Header:           rawHeader,
			Timeout:          rawTimeout,
			Insecure:         rawInsecure,
			AllowHttp:        rawAllowHttp,
			Dpop:             rawDpop,
			DpopKey:          rawDpopKey,
			Verbose:          rawVerbose,
			Trace:            rawTrace,
			NoColor:          rawNoColor,
			Theme:            theme,
			All:              rawAll,
		}

		return tokenClear(cmd.Context(), cmd, newIO(cmd), p)
	}

	return cmd
}

func NewTokenCommand(
	tokenGet TokenGetHandler,
	tokenRefresh TokenRefreshHandler,
	tokenInspect TokenInspectHandler,
	tokenIntrospect TokenIntrospectHandler,
	tokenRevoke TokenRevokeHandler,
	tokenExpect TokenExpectHandler,
	tokenStatus TokenStatusHandler,
	tokenClear TokenClearHandler,
) TokenCommand {
	cmd := &cobra.Command{
		Use:     "token",
		Short:   "Obtain, decode, verify, introspect and revoke tokens.",
		Aliases: []string{"tok"},
		Args:    groupArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return cmd.Help()
		},
	}
	cmd.AddCommand(
		newTokenGetCommand(tokenGet),
		newTokenRefreshCommand(tokenRefresh),
		newTokenInspectCommand(tokenInspect),
		newTokenIntrospectCommand(tokenIntrospect),
		newTokenRevokeCommand(tokenRevoke),
		newTokenExpectCommand(tokenExpect),
		newTokenStatusCommand(tokenStatus),
		newTokenClearCommand(tokenClear),
	)
	return TokenCommand(cmd)
}

type TokenCommand *cobra.Command
